"use client";

import { ChangeEvent, useMemo, useRef, useState } from "react";
import readXlsxFile from "read-excel-file";
import { AlertTriangle, Check, Download, Globe2, Plus, Search, Sparkles, Upload, X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { store } from "@/lib/storefront-data";

export type ImportedProduct = { id:string; name:string; brand:string; category:string; price:number; stock:number; image:string; active:boolean };
type Brand = { name:string; domain:string; slug:string };
type RowStatus = "ready" | "corrected" | "review";
type ImportRow = ImportedProduct & { sku:string; compareAt:number|null; description:string; status:RowStatus; notes:string[]; selected:boolean };

const BRAND_DIRECTORY:Brand[] = [
  ["Apple","apple.com","apple"],["Samsung","samsung.com","samsung"],["Nike","nike.com","nike"],["Adidas","adidas.com","adidas"],
  ["Sony","sony.com","sony"],["Xiaomi","mi.com","xiaomi"],["HP","hp.com","hp"],["Dell","dell.com","dell"],
  ["Lenovo","lenovo.com","lenovo"],["Huawei","huawei.com","huawei"],["Puma","puma.com","puma"],["Philips","philips.com","philips"],
  ["Dyson","dyson.com","dyson"],["L'Oréal","loreal.com","loreal"],["Maybelline","maybelline.com","maybelline"],["LEGO","lego.com","lego"],
  ["Canon","canon.com","canon"],["JBL","jbl.com","jbl"],["Anker","anker.com","anker"],["Haier","haier.com","haier"]
].map(([name,domain,slug])=>({name,domain,slug}));

const logo = (brand:Brand) => `https://cdn.simpleicons.org/${brand.slug}/14233a`;
const clean = (value:unknown) => String(value ?? "").trim();
const slugify = (value:string) => value.toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const titleCase = (value:string) => value.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const num = (value:unknown) => Number(String(value ?? "0").replace(/[^0-9.-]/g,"")) || 0;
const headerKey = (value:unknown) => slugify(clean(value)).replace(/-/g,"_");

function levenshtein(a:string,b:string){const m=Array.from({length:b.length+1},(_,i)=>[i]);for(let j=0;j<=a.length;j++)m[0][j]=j;for(let i=1;i<=b.length;i++)for(let j=1;j<=a.length;j++)m[i][j]=b[i-1]===a[j-1]?m[i-1][j-1]:Math.min(m[i-1][j-1],m[i][j-1],m[i-1][j])+1;return m[b.length][a.length]}
function matchBrand(input:string){const q=input.toLowerCase();return BRAND_DIRECTORY.map(b=>({b,d:levenshtein(q,b.name.toLowerCase())})).sort((a,b)=>a.d-b.d)[0]}
function matchCategory(input:string){const q=slugify(input);return store.categories.find(c=>c.slug===q||slugify(c.name)===q)||store.categories.find(c=>c.slug.includes(q)||q.includes(c.slug))}

export function BrandsManager({supabaseMode,notify}:{supabaseMode?:boolean;notify:(s:string)=>void}){
  const [query,setQuery]=useState(""),[saved,setSaved]=useState<Brand[]>([]),[selected,setSelected]=useState<Brand|null>(null),[saving,setSaving]=useState(false);
  const matches=useMemo(()=>{const q=query.trim().toLowerCase();return (q?BRAND_DIRECTORY.filter(b=>b.name.toLowerCase().includes(q)||b.domain.includes(q)):BRAND_DIRECTORY).slice(0,8)},[query]);
  async function addBrand(){if(!selected)return;setSaving(true);if(supabaseMode){const {error}=await supabase.from("brands").upsert({name:selected.name,slug:slugify(selected.name),domain:selected.domain,logo_url:logo(selected),is_active:true},{onConflict:"slug"});if(error){notify(error.message.includes("brands")?"Run the brand/import database upgrade first.":error.message);setSaving(false);return}}setSaved(all=>all.some(b=>b.name===selected.name)?all:[selected,...all]);notify(`${selected.name} added to brand library`);setSelected(null);setQuery("");setSaving(false)}
  return <section className="catalog-tool-page"><div className="admin-page-action"><div><h2>Brand library</h2><p>Find a recognised brand, verify its official domain and save its logo in one click.</p></div><span className="catalog-safe"><Globe2/> Verified directory</span></div><div className="brand-manager-grid"><article className="brand-search-card"><label>Search brand name</label><div className="brand-search-input"><Search/><input value={query} onChange={e=>{setQuery(e.target.value);setSelected(null)}} placeholder="Try Apple, Samsung, Nike…"/></div><p className="tool-hint">Results use a curated online brand directory. You can verify the official domain before saving.</p><div className="brand-results">{matches.map(b=><button key={b.name} className={selected?.name===b.name?"selected":""} onClick={()=>setSelected(b)}><span><img src={logo(b)} alt="" onError={e=>{e.currentTarget.style.display="none"}}/></span><div><b>{b.name}</b><small>{b.domain}</small></div>{selected?.name===b.name?<Check/>:<Plus/>}</button>)}</div></article><article className="brand-preview-card">{selected?<><span className="brand-logo-large"><img src={logo(selected)} alt={`${selected.name} logo`}/></span><small>BRAND PREVIEW</small><h3>{selected.name}</h3><a href={`https://${selected.domain}`} target="_blank" rel="noreferrer">{selected.domain}</a><button className="admin-primary" disabled={saving} onClick={addBrand}>{saving?"Saving…":"Add brand to catalogue"}</button></>:<div className="brand-empty"><Sparkles/><h3>Select a brand</h3><p>Name, official domain and logo will be filled automatically.</p></div>}</article></div>{saved.length>0&&<div className="saved-brands"><h3>Recently added</h3>{saved.map(b=><span key={b.name}><img src={logo(b)} alt=""/><b>{b.name}</b></span>)}</div>}</section>
}

export function SmartImportModal({close,supabaseMode,onImported,notify}:{close:()=>void;supabaseMode?:boolean;onImported:(rows:ImportedProduct[])=>void;notify:(s:string)=>void}){
  const input=useRef<HTMLInputElement>(null),[rows,setRows]=useState<ImportRow[]>([]),[filename,setFilename]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function choose(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setFilename(file.name);setError("");try{let matrix:unknown[][]=[];if(file.name.toLowerCase().endsWith(".csv")){const text=await file.text();matrix=text.split(/\r?\n/).filter(Boolean).map(line=>line.split(",").map(cell=>cell.replace(/^"|"$/g,"").trim()))}else matrix=(await readXlsxFile(file)) as unknown[][];setRows(normalizeRows(matrix))}catch{setError("File read nahi ho saki. Valid .xlsx ya .csv template upload karein.")}}
  function normalizeRows(matrix:unknown[][]):ImportRow[]{if(matrix.length<2)return[];const headers=matrix[0].map(headerKey);return matrix.slice(1).filter(r=>r.some(Boolean)).map((r,index)=>{const record=Object.fromEntries(headers.map((h,i)=>[h,r[i]])) as Record<string,unknown>;let name=clean(record.product_name||record.name),brand=clean(record.brand),category=clean(record.category);const price=num(record.price),stock=Math.max(0,Math.round(num(record.stock||record.quantity))),image=clean(record.image_url||record.image||record.images),notes:string[]=[];const brandMatch=brand&&matchBrand(brand);if(brandMatch&&brandMatch.d>0&&brandMatch.d<=2){notes.push(`Brand corrected: ${brand} → ${brandMatch.b.name}`);brand=brandMatch.b.name}const cat=matchCategory(category);if(cat&&cat.slug!==slugify(category)){notes.push(`Category matched: ${category} → ${cat.name}`);category=cat.slug}else if(cat)category=cat.slug;if(name&&name===name.toUpperCase()){name=titleCase(name);notes.push("Product name formatting corrected")}if(!category||!cat)notes.push("Choose a valid category");if(!name)notes.push("Product name missing");if(!brand)notes.push("Brand missing");if(price<=0)notes.push("Valid price missing");if(!image)notes.push("Product image URL missing");const hasCritical=!name||!brand||price<=0||!image||!cat;return{id:`import-${Date.now()}-${index}`,name,brand,category:cat?.slug||category,price,stock,image,active:false,sku:clean(record.sku),compareAt:num(record.compare_at||record.old_price)||null,description:clean(record.description),status:hasCritical?"review":notes.length?"corrected":"ready",notes,selected:!hasCritical}})}
  async function importRows(){const chosen=rows.filter(r=>r.selected&&r.status!=="review");if(!chosen.length){setError("Import ke liye kam az kam ek Ready row select karein.");return}setBusy(true);let imported:ImportedProduct[]=chosen.map(r=>({id:r.id,name:r.name,brand:r.brand,category:r.category,price:r.price,stock:r.stock,image:r.image,active:false}));if(supabaseMode){const {data:categories}=await supabase.from("categories").select("id,slug");const categoryRows=(categories||[]) as {id:string;slug:string}[];const payload=chosen.map(r=>({name:r.name,slug:`${slugify(r.name)}-${Date.now().toString().slice(-6)}-${Math.random().toString(36).slice(2,5)}`,brand:r.brand,category_id:categoryRows.find(c=>c.slug===r.category)?.id||null,price:r.price,compare_at:r.compareAt,description:r.description||null,images:[r.image],stock:r.stock,sections:["new"],is_active:false}));const {data,error:dbError}=await supabase.from("products").insert(payload).select();if(dbError){setError(dbError.message);setBusy(false);return}const created=(data||[]) as {id:string;name:string;brand:string;price:number;stock:number;images:string[]}[];imported=created.map(p=>({id:p.id,name:p.name,brand:p.brand,category:chosen.find(x=>x.name===p.name)?.category||"",price:Number(p.price),stock:p.stock,image:p.images?.[0]||"",active:false}))}onImported(imported);notify(`${imported.length} products imported as drafts`);setBusy(false);close()}
  const selectedCount=rows.filter(r=>r.selected&&r.status!=="review").length;
  return <div className="admin-modal-shade" onClick={close}><section className="smart-import-modal" onClick={e=>e.stopPropagation()}><header><div><span>AUTOMATIC CATALOGUE BUILDER</span><h2>Smart product import</h2><p>Upload Excel or CSV, review automatic corrections, then import approved rows as drafts.</p></div><button onClick={close}><X/></button></header>{!rows.length?<div className="import-start"><button className="import-drop" onClick={()=>input.current?.click()}><Upload/><b>Choose Excel or CSV file</b><span>.xlsx and .csv · maximum 2,000 rows</span></button><input ref={input} hidden type="file" accept=".xlsx,.csv" onChange={choose}/><a href="/product-import-template.csv" download><Download/> Download import template</a><div className="import-rules"><span><Check/> Names and brand spelling cleaned</span><span><Check/> Categories matched to your store</span><span><AlertTriangle/> Missing facts held for review</span></div>{error&&<p className="import-error">{error}</p>}</div>:<><div className="import-summary"><div><b>{filename}</b><span>{rows.length} rows detected</span></div><span className="ready">{rows.filter(r=>r.status==="ready").length} ready</span><span className="corrected">{rows.filter(r=>r.status==="corrected").length} corrected</span><span className="review">{rows.filter(r=>r.status==="review").length} need review</span><button onClick={()=>{setRows([]);setFilename("")}}>Change file</button></div><div className="import-table"><table><thead><tr><th></th><th>Product</th><th>Brand</th><th>Category</th><th>Price / Stock</th><th>Check</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><input type="checkbox" checked={r.selected} disabled={r.status==="review"} onChange={e=>setRows(all=>all.map(x=>x.id===r.id?{...x,selected:e.target.checked}:x))}/></td><td><div className="import-product">{r.image?<img src={r.image} alt=""/>:<span/>}<b>{r.name||"Missing name"}</b></div></td><td>{r.brand||"—"}</td><td>{r.category||"—"}</td><td><b>Rs. {r.price.toLocaleString()}</b><small>{r.stock} stock</small></td><td><span className={`row-state ${r.status}`}>{r.status}</span>{r.notes.length>0&&<small className="row-notes">{r.notes.join(" · ")}</small>}</td></tr>)}</tbody></table></div>{error&&<p className="import-error">{error}</p>}<footer><p><b>{selectedCount}</b> approved products will be saved as drafts.</p><button onClick={close}>Cancel</button><button className="admin-primary" disabled={busy||!selectedCount} onClick={importRows}>{busy?"Importing…":`Import ${selectedCount} products`}</button></footer></>}</section></div>
}
