"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {FormEvent,useEffect,useRef,useState} from "react";
import {Bot,CircleUserRound,Headphones,Heart,House,Menu,MessageCircle,Search,Send,ShoppingBag,Smartphone,Truck,Shirt,Sparkles,X,ChevronRight} from "lucide-react";
import {useCatalog} from "./catalog-provider";
import {useStorefront} from "./storefront-provider";

const categoryIcons=[Sparkles,Shirt,Smartphone,House,Sparkles,Headphones,ShoppingBag,Heart];
export function Logo(){return <Link className="logo" href="/"><b>1</b><span>Click<i>Mela</i></span></Link>}

export function SiteHeader(){
 const {cartCount,wishlist}=useStorefront();const {catalog:store}=useCatalog();const [q,setQ]=useState(""),[menu,setMenu]=useState(false);const router=useRouter();
 const submit=(e:FormEvent)=>{e.preventDefault();router.push(q.trim()?`/search?q=${encodeURIComponent(q.trim())}`:"/search")};
 return <>
  <div className="announcement"><div className="ticker"><span><Truck/> Delivery all over Pakistan</span><span>|</span><span>Cash on Delivery Available</span><span aria-hidden><Truck/> Delivery all over Pakistan</span><span aria-hidden>|</span><span aria-hidden>Cash on Delivery Available</span></div></div>
  <header className="main-header"><button className="menu-button" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu/></button><Logo/><form className="search" onSubmit={submit}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search for products, brands and more…"/><button aria-label="Search"><Search/></button></form><nav className="actions"><Link href="/account"><CircleUserRound/><span>Account</span></Link><Link href="/wishlist"><Heart/><span>Wishlist</span>{wishlist.length>0&&<b>{wishlist.length}</b>}</Link><Link href="/cart"><ShoppingBag/><span>Cart</span>{cartCount>0&&<b>{cartCount}</b>}</Link></nav></header>
  <nav className="main-nav"><div className="category-menu"><button type="button" onClick={()=>setMenu(true)}><Menu/> Shop by category <ChevronRight/></button><div className="category-dropdown">{store.categories.map((c,i)=>{const Icon=categoryIcons[i]||Sparkles;return <Link key={c.id} href={`/category/${c.slug}`}><Icon/><span>{c.name}</span><ChevronRight/></Link>})}</div></div><Link className="custom-nav-link" href="/custom-order">Custom Order</Link><Link className="deal-link" href="/#flash">Flash Deals</Link><Link href="/search?q=best">Best Sellers</Link><Link href="/search?q=new">New Arrivals</Link><Link href="/brands">Brands</Link><Link href="/track-order">Track Order</Link><Link href="/help">Help Center</Link></nav>
  <nav className="category-bar">{store.categories.map((c,i)=>{const Icon=categoryIcons[i]||Sparkles;return <Link key={c.id} href={`/category/${c.slug}`}><Icon/>{c.name}</Link>})}</nav>
  {menu&&<div className="drawer-shade" onClick={()=>setMenu(false)}><aside onClick={e=>e.stopPropagation()}><div><Logo/><button onClick={()=>setMenu(false)} aria-label="Close menu"><X/></button></div><p>Shop categories</p>{store.categories.map(c=><Link onClick={()=>setMenu(false)} key={c.id} href={`/category/${c.slug}`}>{c.name}<ChevronRight/></Link>)}<Link onClick={()=>setMenu(false)} href="/account">My account <CircleUserRound/></Link><Link onClick={()=>setMenu(false)} href="/wishlist">Wishlist <Heart/></Link><Link onClick={()=>setMenu(false)} href="/cart">Shopping cart <ShoppingBag/></Link></aside></div>}
 </>
}

export function SiteFooter(){return <footer>
 <div className="newsletter"><div><span className="mail-mark">✉</span><p><b>Stay in the loop</b><small>Subscribe to get updates on new arrivals,<br/>exclusive offers and more.</small></p></div><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="Enter your email address"/><button>Subscribe</button></form></div>
 <div className="footer-inner"><div><Logo/><p>Your one-click marketplace for fashion, beauty, electronics, home and more. Delivered with trust across Pakistan.</p><span className="social-links">f&nbsp;&nbsp; ◎ &nbsp;&nbsp;▶</span></div><div><h3>Customer Service</h3><Link href="/help">Help Center</Link><Link href="/help">How to Buy</Link><Link href="/track-order">Track Order</Link><Link href="/returns">Returns & Refunds</Link><Link href="/contact">Contact Us</Link></div><div><h3>Company & Legal</h3><Link href="/brands">Our Brands</Link><Link href="/contact">About 1ClickMela</Link><Link href="/terms">Terms & Conditions</Link><Link href="/privacy">Privacy Policy</Link><Link href="/shipping">Shipping Policy</Link></div><div><h3>My Account</h3><Link href="/account">My Orders</Link><Link href="/wishlist">Wishlist</Link><Link href="/account">My Profile</Link><Link href="/account">Account Settings</Link></div><div><h3>Download Our App</h3><div className="app-badges"><span>▶ <b>GET IT ON<br/>Google Play</b></span><span>● <b>Download on the<br/>App Store</b></span></div></div></div>
 <div className="copyright"><span>© {new Date().getFullYear()} 1ClickMela. All Rights Reserved.</span><strong>VISA&nbsp;&nbsp; ◉◉ &nbsp;&nbsp; easypaisa &nbsp;&nbsp; JazzCash</strong></div>
 </footer>}
type ChatMessage={from:"bot"|"user";text:string};
function assistantReply(value:string){const q=value.toLowerCase();if(/order|track|parcel/.test(q))return "You can track an order from Track Order using your reference number. For a new purchase, add items to cart and choose Cash on Delivery at checkout.";if(/return|refund|exchange/.test(q))return "Unused eligible items can be requested for return within 7 days of delivery. Open our Returns page for conditions and the request process.";if(/deliver|shipping|city|lahore|karachi|islamabad/.test(q))return "We deliver across Pakistan. Standard delivery is usually 3–7 working days; exact timing depends on your city and product availability.";if(/custom|find|source/.test(q))return "Use Custom Order to send the product name, link, pictures and target budget. Our sourcing team will review the request and contact you with a quote.";if(/payment|cash|cod/.test(q))return "Cash on Delivery is currently available. You pay in cash when the parcel reaches you—no advance online payment is required.";if(/account|login|sign/.test(q))return "Account access is available from the Account button. Secure cloud sync will be added during the Supabase phase.";return "I can help with orders, delivery, returns, Cash on Delivery, accounts and custom product requests. Choose a topic below or describe what you need."}
export function SupportChat(){const [open,setOpen]=useState(false),[value,setValue]=useState(""),[typing,setTyping]=useState(false),[messages,setMessages]=useState<ChatMessage[]>([{from:"bot",text:"Assalam-o-Alaikum! I’m Mela Assistant. How can I help with your shopping today?"}]);const end=useRef<HTMLDivElement>(null);useEffect(()=>end.current?.scrollIntoView({behavior:"smooth"}),[messages,typing]);function send(text=value){const clean=text.trim();if(!clean||typing)return;setMessages(m=>[...m,{from:"user",text:clean}]);setValue("");setTyping(true);setTimeout(()=>{setMessages(m=>[...m,{from:"bot",text:assistantReply(clean)}]);setTyping(false)},650)}return <div className="support-chat"><button className="chat-launcher" onClick={()=>setOpen(!open)} aria-label={open?"Close support chat":"Open support chat"}>{open?<X/>:<MessageCircle/>}<span>Chat support</span></button>{open&&<section className="chat-panel" aria-label="Mela Assistant"><header><div><span><Bot/></span><p><b>Mela Assistant</b><small><i/> Online · Instant help</small></p></div><button onClick={()=>setOpen(false)} aria-label="Close chat"><X/></button></header><div className="chat-messages">{messages.map((m,i)=><p className={m.from} key={i}>{m.text}</p>)}{typing&&<p className="bot typing"><i/><i/><i/></p>}<div ref={end}/></div><div className="quick-replies">{["Track my order","Delivery time","Return policy","Custom order"].map(x=><button onClick={()=>send(x)} key={x}>{x}</button>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Type your question…" aria-label="Chat message"/><button aria-label="Send message"><Send/></button></form><small className="chat-note">Automated shopping assistance · Never share passwords or card details.</small></section>}</div>}
export function PageShell({children}:{children:React.ReactNode}){return <><SiteHeader/><main>{children}</main><SiteFooter/><SupportChat/></>}
